policy_type: 'sac_fm'
model_path: 'safebench/agent/model_ckpt/sac_fm'
model_id: 0
results_folder_path: ''
obs_type: 0

train_episode: 2000
eval_in_train_freq: 1
save_freq: 5
buffer_capacity: 35000
buffer_start_training: 2000

lr: 5.0e-4
tau: 0.005
update_iteration: 1
gamma: 0.99
batch_size: 32
min_Val: 1.0e-7
